services:
  api:
    build:
      context: ../../api
      dockerfile: ../infra/docker/api.Dockerfile
    container_name: equipment-api
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ../../api:/app
      - ../../database:/database

  frontend:
    build:
      context: ../../frontend
      dockerfile: ../infra/docker/frontend.Dockerfile
    container_name: equipment-frontend
    working_dir: /app
    environment:
      - VITE_API_PROXY_TARGET=http://api:8000
    ports:
      - "5173:5173"
    volumes:
      - ../../frontend:/app
    depends_on:
      - api
